export const styles = {
  app: {
    minHeight: "100vh",
    maxWidth: 480,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    background: "#F7F6F3",
  },
  loadingScreen: { display: "flex", alignItems: "center", justifyContent: "center", height: "100vh", color: "#8A8A86", fontSize: 14 },

  // Login
  loginScreen: { display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", padding: 20 },
  loginCard: { background: "#fff", borderRadius: 16, padding: 28, width: "100%", maxWidth: 360, border: "1px solid #ECEAE3" },
  loginBrand: { fontWeight: 800, fontSize: 22, color: "#1F4D45", textAlign: "center" },
  loginSub: { fontSize: 13, color: "#9A9A94", textAlign: "center", marginBottom: 20, marginTop: 4 },
  errorBox: { background: "#FBF1E7", color: "#7A4B26", fontSize: 12.5, padding: "8px 12px", borderRadius: 8, margin: "10px 0" },
  linkBtn: { width: "100%", background: "transparent", border: "none", color: "#1F4D45", fontSize: 13, fontWeight: 600, marginTop: 14, cursor: "pointer", textAlign: "center" },

  // Top bar
  topbar: { background: "#FFFFFF", borderBottom: "1px solid #E8E6DF", position: "sticky", top: 0, zIndex: 10 },
  topbarRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 18px 10px" },
  brand: { fontWeight: 800, fontSize: 17, letterSpacing: "-0.01em", color: "#1F4D45" },
  brandSub: { fontSize: 11.5, color: "#9A9A94", marginTop: 1 },
  statusPill: { display: "flex", alignItems: "center", gap: 6, border: "none", borderRadius: 20, padding: "6px 12px", fontSize: 12, fontWeight: 600 },
  statusOn: { background: "#E4EFE9", color: "#1F4D45" },
  statusOff: { background: "#F6E6DA", color: "#A85A2A" },
  iconBtn: { background: "#F1EFE8", border: "none", borderRadius: 8, padding: 7, cursor: "pointer", display: "flex", color: "#5C5C58" },
  syncBar: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "#FBF1E7", padding: "8px 18px", fontSize: 12.5, color: "#7A4B26", borderTop: "1px solid #F0DDC8" },
  syncBarLeft: { display: "flex", alignItems: "center", gap: 6 },
  syncBtn: { display: "flex", alignItems: "center", gap: 5, background: "#1F4D45", color: "#fff", border: "none", borderRadius: 8, padding: "6px 10px", fontSize: 12, fontWeight: 600, cursor: "pointer" },

  content: { flex: 1, padding: "16px 16px 90px", overflowY: "auto" },
  h1: { fontSize: 20, fontWeight: 800, letterSpacing: "-0.01em", margin: 0 },
  listHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  backHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14 },
  backHeaderRow: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  backBtn: { background: "#fff", border: "1px solid #E8E6DF", borderRadius: 10, padding: 6, cursor: "pointer", display: "flex" },
  editLinkBtn: { background: "#1F4D45", color: "#fff", border: "none", borderRadius: 9, padding: "7px 14px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  dangerLinkBtn: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", width: "100%", background: "transparent", color: "#B8763E", border: "1px solid #F0DDC8", borderRadius: 12, padding: "12px 0", fontSize: 13.5, fontWeight: 600, marginTop: 16, cursor: "pointer" },
  fabFullWidth: { width: "100%", background: "#1F4D45", color: "#fff", border: "none", borderRadius: 12, padding: "12px 0", fontSize: 14, fontWeight: 700, marginBottom: 18, cursor: "pointer" },
  fabInline: { display: "flex", alignItems: "center", gap: 5, background: "#1F4D45", color: "#fff", border: "none", borderRadius: 10, padding: "8px 13px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  sectionTitle: { fontSize: 12.5, fontWeight: 700, color: "#8A8A86", textTransform: "uppercase", letterSpacing: "0.04em", margin: "20px 4px 8px" },
  emptyHint: { color: "#9A9A94", fontSize: 13.5, padding: "24px 8px", textAlign: "center" },
  card: { background: "#fff", borderRadius: 14, padding: "4px 16px", border: "1px solid #ECEAE3" },
  rowCard: { display: "flex", alignItems: "center", gap: 12, background: "#fff", borderRadius: 12, padding: "12px 14px", border: "1px solid #ECEAE3", marginBottom: 8, fontSize: 14 },
  listItem: { display: "flex", alignItems: "center", gap: 12, width: "100%", background: "#fff", borderRadius: 12, padding: "12px 14px", border: "1px solid #ECEAE3", marginBottom: 8, cursor: "pointer", textAlign: "left" },
  avatar: { width: 38, height: 38, borderRadius: 10, background: "#E4EFE9", color: "#1F4D45", fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  listItemTitle: { fontWeight: 600, fontSize: 14.5 },
  listItemSub: { fontSize: 12.5, color: "#9A9A94", marginTop: 2 },
  field: { display: "block", padding: "10px 0", borderBottom: "1px solid #F1EFE8" },
  fieldLabel: { fontSize: 11.5, color: "#9A9A94", marginBottom: 4, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.03em" },
  fieldValue: { fontSize: 14.5, color: "#22231F" },
  input: { width: "100%", border: "none", outline: "none", fontSize: 15, color: "#22231F", background: "transparent", padding: 0, fontFamily: "inherit" },
  select: { width: "100%", border: "none", outline: "none", fontSize: 15, color: "#22231F", background: "transparent", padding: 0, fontFamily: "inherit" },
  divider: { height: 1, background: "#F1EFE8", margin: "4px 0" },
  errorText: { display: "flex", alignItems: "center", gap: 5, fontSize: 12, color: "#B8763E", padding: "4px 0" },
  offlineNotice: { display: "flex", alignItems: "flex-start", gap: 8, background: "#FBF1E7", color: "#7A4B26", fontSize: 12.5, padding: "10px 12px", borderRadius: 10, marginBottom: 12, lineHeight: 1.4 },
  primaryBtn: { width: "100%", background: "#1F4D45", color: "#fff", border: "none", borderRadius: 12, padding: "14px 0", fontSize: 15, fontWeight: 700, marginTop: 20, cursor: "pointer" },
  primaryBtnDisabled: { background: "#D8D6CD", color: "#A8A6A0", cursor: "not-allowed" },
  secondaryBtn: { width: "100%", background: "#fff", color: "#1F4D45", border: "1.5px solid #1F4D45", borderRadius: 12, padding: "12px 0", fontSize: 14, fontWeight: 700, marginTop: 10, cursor: "pointer" },
  tag: { fontSize: 10.5, fontWeight: 700, padding: "3px 8px", borderRadius: 6 },
  tagGreen: { background: "#E4EFE9", color: "#1F4D45" },
  tagOrange: { background: "#F6E6DA", color: "#A85A2A" },
  tagRed: { background: "#FBE2DC", color: "#C24E3A" },
  tagSync: { display: "flex", alignItems: "center", gap: 3, fontSize: 9.5, color: "#B8763E" },
  viewToggle: { display: "flex", background: "#F1EFE8", borderRadius: 9, padding: 3, gap: 2, marginBottom: 16 },
  viewToggleBtn: { border: "none", background: "transparent", padding: "8px 14px", borderRadius: 7, cursor: "pointer", color: "#8A8A86", fontSize: 13, fontWeight: 600, flex: 1 },
  viewToggleBtnActive: { background: "#fff", color: "#1F4D45", boxShadow: "0 1px 2px rgba(0,0,0,0.06)" },
  bottomNav: { display: "flex", background: "#fff", borderTop: "1px solid #E8E6DF", position: "sticky", bottom: 0, paddingBottom: 6, overflowX: "auto" },
  navBtn: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "10px 0 4px", background: "transparent", border: "none", fontSize: 9.5, cursor: "pointer", color: "#8A8A86", minWidth: 56 },
  navBtnActive: { color: "#1F4D45" },
  toast: { position: "fixed", bottom: 78, left: "50%", transform: "translateX(-50%)", background: "#22231F", color: "#fff", padding: "10px 18px", borderRadius: 10, fontSize: 13, maxWidth: 360, textAlign: "center", boxShadow: "0 8px 24px rgba(0,0,0,0.2)", zIndex: 50 },

  // Indicadores do painel
  kpiGrid: { display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 6 },
  kpiCard: { background: "#fff", borderRadius: 12, border: "1px solid #ECEAE3", padding: "12px 14px", flex: "1 1 calc(50% - 5px)", minWidth: 120 },
  kpiHeader: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#5C5C58", marginBottom: 6 },
  kpiValor: { fontSize: 16.5, fontWeight: 800, color: "#22231F" },
  alertaCard: { display: "flex", alignItems: "flex-start", gap: 10, background: "#FBF1E7", borderRadius: 12, padding: "12px 14px", border: "1px solid #F0DDC8", marginBottom: 8 },
  alertaTitulo: { fontSize: 13.5, fontWeight: 700, color: "#7A4B26" },
  alertaSub: { fontSize: 12, color: "#9A7857", marginTop: 2 },

  // Captura RFID / balança
  scanBox: { display: "flex", alignItems: "center", gap: 10, background: "#E4EFE9", border: "1.5px dashed #1F4D45", borderRadius: 12, padding: "12px 14px", marginBottom: 12 },
  scanBoxText: { fontSize: 12.5, color: "#1F4D45", flex: 1 },
  scanBoxActive: { background: "#1F4D45" },
  scaleBtn: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, width: "100%", background: "#fff", color: "#1F4D45", border: "1.5px solid #1F4D45", borderRadius: 12, padding: "12px 0", fontSize: 14, fontWeight: 700, cursor: "pointer" },
  scaleBtnConnected: { background: "#1F4D45", color: "#fff" },
  hardwareHint: { fontSize: 11.5, color: "#9A9A94", textAlign: "center", marginTop: 8, lineHeight: 1.4 },

  // Timeline (ficha individual)
  timelineItem: { display: "flex", gap: 12, paddingBottom: 16, position: "relative" },
  timelineDot: { width: 10, height: 10, borderRadius: "50%", background: "#1F4D45", marginTop: 4, flexShrink: 0 },
  timelineLine: { position: "absolute", left: 4, top: 14, bottom: -6, width: 1, background: "#E8E6DF" },
  timelineContent: { flex: 1 },
  timelineTitulo: { fontSize: 13.5, fontWeight: 600 },
  timelineData: { fontSize: 11.5, color: "#9A9A94", marginTop: 1 },
};
